Signed-off-by: Andreas Müller <mulan04.0120@gmail.com>

diff --git a/.github/workflows/BILLY.yml b/.github/workflows/BILLY.yml
--- a/.github/workflows/BILLY.yml
+++ b/.github/workflows/BILLY.yml
@@ -43,22 +43,26 @@ jobs:
 
       - name: Build docker image
         run: docker build -t aquasupportemea/insecure-bank-app:${{ github.sha }} .
+
+      - name: Billy health
+        run: |
+          ./billy health
         
-      # - name: SBOM Generation - Manifest Generation
-        # run: |
-          # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
-          # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          # if ! cat install.sh.checksum | sha256sum --check; then
-          # echo "install.sh checksum failed"
-          # exit 1
-          # fi
-          # BINDIR="." sh install.sh
-          # rm install.sh install.sh.checksum
-          # # export OVERRIDE_RUN_ID=696969
-          # ./billy generate \
-            # --access-token "${{ secrets.GITHUB_TOKEN }}" \
-            # --aqua-key "${{ secrets.AQUA_KEY }}" \
-            # --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-            # --cspm-url https://eu-1.api.cloudsploit.com \
-            # --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
+      - name: SBOM Generation - Manifest Generation
+        run: |
+          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          # export OVERRIDE_RUN_ID=696969
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --cspm-url https://eu-1.api.cloudsploit.com \
+            --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
