Signed-off-by: Andreas Müller <mulan04.0120@gmail.com>

diff --git a/.github/workflows/BILLY.yml b/.github/workflows/BILLY.yml
--- a/.github/workflows/BILLY.yml
+++ b/.github/workflows/BILLY.yml
@@ -46,36 +46,36 @@ jobs:
 
       - name: SBOM Generation - Manifest Generation
         run: |
-          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
-          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | sha256sum --check; then
-          echo "install.sh checksum failed"
-          exit 1
-          fi
-          BINDIR="." sh install.sh
-          rm install.sh install.sh.checksum
-          # export OVERRIDE_RUN_ID=696969
-          # ./billy generate \
+          # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+          # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          # if ! cat install.sh.checksum | sha256sum --check; then
+          # echo "install.sh checksum failed"
+          # exit 1
+          # fi
+          # BINDIR="." sh install.sh
+          # rm install.sh install.sh.checksum
+          # # export OVERRIDE_RUN_ID=696969
+          # # ./billy generate \
+            # # --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            # # --aqua-key "${{ secrets.AQUA_KEY }}" \
+            # # --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            # # --cspm-url https://eu-1.api.cloudsploit.com \
+            # # --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
+          # ./billy health \
             # --access-token "${{ secrets.GITHUB_TOKEN }}" \
             # --aqua-key "${{ secrets.AQUA_KEY }}" \
             # --aqua-secret "${{ secrets.AQUA_SECRET }}" \
             # --cspm-url https://eu-1.api.cloudsploit.com \
             # --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
-          ./billy health \
-            --access-token "${{ secrets.GITHUB_TOKEN }}" \
-            --aqua-key "${{ secrets.AQUA_KEY }}" \
-            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-            --cspm-url https://eu-1.api.cloudsploit.com \
-            --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
           docker image ls
 
       - name: Run private container
         uses: ./.github/actions/Aqua_Image_Scanner
         with:
           registry: registry.example.com
-          username: ${{ secrets.REGISTRY_USER }}
-          password: ${{ secrets.REGISTRY_PASSWORD }}
+          username: ${{ secrets.AQUA_USERNAME }}
+          password: ${{ secrets.AQUA_PASSWORD }}
           image: scanner
           tag: "10"
           run_args: "-e ENV=prod -p 8080:8080"
